### ISSUE TITLE
Question about the input size

### ISSUE THREAD

**Issue by thuangb** [andreas128/NTIRE22_Learning_SR_Space#1]
Hi, I have a question 
Currently, I have trained a model  that only works with fixed size input. So in evaluation step, I resize the input to a fixed size, e.g., 256 x 256 for 8X and 512 x 512 for 4X. Is this acceptable ?

**Comment by andreas128** [comment]
Sorry for the late reply! We sent the instructions for the testing via mail.

Your method needs to super-resolve arbitrary sizes. A popular way to achieve this property, is by using a convolutional neural network.

**Comment by thuangb** [comment]
Then you should include this in the rule else someone will end up like me ...
